### ISSUE TITLE
cannot enc data

### ISSUE THREAD

**Issue by calidion** [quartzjer/ursa#91] opened 2015-06-04 08:58 UTC
Error: error:0407906E:rsa routines:RSA_padding_add_PKCS1_OAEP:data too large for key size

**Comment by calidion** [comment] 2015-06-04 09:18
string needs to be encrypted.

private key is 2048 bit long modulus 

```
_input_charset=utf-8&airticket=&body=没有什么可以更多的了&extern_token=&it_b_pay=90m&notify_url=http://api.t1bao.com/alipay/notify&otherfee=&out_trade_no=订单号：20150529142335-EJTG&partner=2088911456277187&payment_type=1&return_url=http://api.t1bao.com/alipay/callback&seller_id=renwenxin@t1bao.com&show_url=&subject=田一块小卖店的订单&total_fee=25.80
```

**Comment by quartzjer** [comment] 2015-06-04 12:31
duplicate of #14

**Closed by quartzjer** 2015-06-04 12:31 UTC

**Comment by calidion** [comment] 2015-06-05 06:45
is there a way to encrypt a string without padding?

**Comment by quartzjer** [comment] 2015-06-05 22:09
Try a streaming encryption like AES :)
